#!/usr/bin/env python3
"""Boundaries for the scheduled acquisition and discovery workflows.

The scheduled workflows in `.github/workflows/scheduled-acquisition.yml` and
`.github/workflows/scheduled-discovery.yml` run the same `dk.py acquire` and
`dk.py discover` entry points a maintainer would, on an ephemeral runner. What
they observed must not vanish with the runner, so a run that changed something
is persisted on a deterministic automation branch and offered as a pull request
for human review. This module is the one place that says what such a run may
persist, and it renders the run's summary from the engine's own report.

It never runs git, never fetches anything and never writes into the tree. The
workflows pipe `git status --porcelain -z` into `check-paths`, read the
allow-list from `paths`, and let git do the committing where every command is
visible in the workflow file. Three things are fixed here and tested:

1. Automation may persist evidence, state and review candidates, plus the
   derived public artifacts that are byte-determined by them and that
   `dk.py validate` requires to be current. Nothing else.
2. A run that changed nothing produces no commit and no pull request.
3. A report whose engine recorded a trusted-knowledge mutation is never
   summarized as a success: the invariant `SOURCE CHANGE != TRUSTED
   KNOWLEDGE CHANGE` is checked again here, after the engine checked it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# The public projections that acquisition or discovery state flows into. They
# are regenerated by `dk.py public-site build`, `dk.py api build` and
# `dk.py release-meta`; the workflow runs those commands and nothing else.
DERIVED_PATHS = (
    "public-site/dataset/manifest.json",
    "public-site/dataset/sources.json",
    "public-api/examples/",
    "release/checksums.json",
)

OPERATIONS = {
    "acquisition": {
        "title": "Scheduled source acquisition",
        "command": "python3 scripts/dk.py acquire --trust authoritative --due",
        "branch": "automation/source-acquisition",
        "evidence_paths": (
            "sources/snapshots/",
            "sources/state/",
            "discovery/candidates/",
        ),
        "report_dir": "acquisition-report",
    },
    "discovery": {
        "title": "Scheduled discovery",
        "command": "python3 scripts/dk.py discover --trust ecosystem --due",
        "branch": "automation/discovery",
        "evidence_paths": (
            "sources/snapshots/",
            "sources/state/",
            "discovery/candidates/",
            "discovery/signals/",
            "discovery/review/",
        ),
        "report_dir": "discovery-report",
    },
}

# What automation must never touch, named so the negative test can say why. The
# allow-list above is what is enforced; this list documents the intent.
FORBIDDEN_EXAMPLES = (
    "knowledge/",
    "rules/",
    "api/",
    "security/",
    "cases/",
    "taxonomy/",
    "schema/",
    "config/",
    "sources/registry.json",
    "public-site/content/",
    "public-site/dataset/domains/",
    "public-site/dataset/search-index.json",
    "release/sbom.json",
    "scripts/",
    "collectors/",
    "dk",
    ".github/",
    "docs/",
    "README.md",
    "CHANGELOG.md",
    "VERSION",
)


class AutomationBoundaryError(Exception):
    """A scheduled run tried to persist something automation may not persist."""


def allowed_paths(operation: str) -> tuple[str, ...]:
    return tuple(OPERATIONS[operation]["evidence_paths"]) + DERIVED_PATHS


def is_allowed(operation: str, path: str) -> bool:
    for prefix in allowed_paths(operation):
        if prefix.endswith("/"):
            if path.startswith(prefix):
                return True
        elif path == prefix:
            return True
    return False


def classify(operation: str, paths: list[str]) -> dict[str, list[str]]:
    allowed, forbidden = [], []
    for path in sorted(set(paths)):
        (allowed if is_allowed(operation, path) else forbidden).append(path)
    return {"allowed": allowed, "forbidden": forbidden}


def parse_porcelain(data: bytes) -> list[str]:
    """Paths from `git status --porcelain -z`.

    Entries are NUL-separated; a rename carries a second NUL-separated field
    (the original path), which is included so a rename out of an allowed path
    is seen as a change to both names.
    """
    paths: list[str] = []
    fields = data.split(b"\x00")
    index = 0
    while index < len(fields):
        entry = fields[index]
        index += 1
        if not entry:
            continue
        status, path = entry[:2], entry[3:]
        paths.append(path.decode("utf-8"))
        if status[:1] in (b"R", b"C") and index < len(fields) and fields[index]:
            paths.append(fields[index].decode("utf-8"))
            index += 1
    return paths


def check_paths(operation: str, paths: list[str]) -> dict[str, list[str]]:
    outcome = classify(operation, paths)
    if outcome["forbidden"]:
        raise AutomationBoundaryError(
            f"{operation} automation may not persist: "
            + ", ".join(outcome["forbidden"])
        )
    return outcome


# --- run summaries ------------------------------------------------------------


def assert_no_trusted_knowledge_mutation(report: dict) -> None:
    if report.get("trusted_knowledge_mutations"):
        raise AutomationBoundaryError(
            "the engine recorded a trusted knowledge mutation; this run must not be persisted"
        )
    digest = report.get("trusted_knowledge_digest") or {}
    if digest and digest.get("before") != digest.get("after"):
        raise AutomationBoundaryError(
            "trusted knowledge digest changed during the run; this run must not be persisted"
        )


def _count(items) -> int:
    return len(items) if isinstance(items, (list, dict)) else 0


def acquisition_counts(report: dict) -> dict[str, int]:
    results = report.get("results", [])
    by_status: dict[str, int] = {}
    for item in results:
        by_status[item["status"]] = by_status.get(item["status"], 0) + 1
    selection = report.get("selection", {})
    skipped = selection.get("skipped", [])
    return {
        "selected": _count(selection.get("selected", [])),
        "not_due": sum(1 for item in skipped if item.get("reason") == "not_due"),
        "attempted": len(results),
        "first_observation": by_status.get("first_observation", 0),
        "unchanged": by_status.get("unchanged", 0),
        "changed": by_status.get("changed", 0),
        "unavailable": by_status.get("unavailable", 0),
        "invalid_or_malformed": by_status.get("invalid_or_malformed", 0),
        "snapshots_created": _count(report.get("snapshots_created", [])),
        "review_candidates_created": _count(report.get("review_candidates_created", [])),
        "review_candidates_reused": _count(report.get("review_candidates_reused", [])),
        "failures": _count(report.get("failures", [])),
        "engine_defects": _count(report.get("engine_defects", [])),
    }


def discovery_counts(report: dict) -> dict[str, int]:
    results = report.get("results", [])
    by_status: dict[str, int] = {}
    for item in results:
        by_status[item["status"]] = by_status.get(item["status"], 0) + 1
    selection = report.get("selection", {})
    return {
        "attempted": len(results),
        "not_due": _count(selection.get("skipped_not_due", [])),
        "observed": by_status.get("observed", 0),
        "unavailable": by_status.get("unavailable", 0),
        "invalid_or_malformed": by_status.get("invalid_or_malformed", 0),
        "signals_created": _count(report.get("signals_created", [])),
        "signals_updated": _count(report.get("signals_updated", [])),
        "signals_reused": _count(report.get("signals_reused", [])),
        "review_work_created": _count(report.get("review_work_created", [])),
        "corroboration_results": _count(report.get("corroboration_results", [])),
        "failures": _count(report.get("failures", [])),
        "engine_defects": _count(report.get("engine_defects", [])),
    }


def counts(operation: str, report: dict) -> dict[str, int]:
    return acquisition_counts(report) if operation == "acquisition" else discovery_counts(report)


PERSISTENCE_OUTCOMES = ("no-op", "pending", "pr-created", "pr-updated")


def summary_markdown(
    operation: str,
    report: dict,
    *,
    persistence: str,
    validate_exit: int | None = None,
    engine_exit: int | None = None,
    branch: str | None = None,
) -> str:
    """The run as the engine reported it. Every number comes from the report."""
    if persistence not in PERSISTENCE_OUTCOMES:
        raise ValueError(f"unknown persistence outcome {persistence!r}")
    assert_no_trusted_knowledge_mutation(report)
    spec = OPERATIONS[operation]
    numbers = counts(operation, report)
    lines = [
        f"## {spec['title']}",
        "",
        f"- run: `{report.get('run_id', '?')}`; command: `{spec['command']}`; dry run: `{report.get('dry_run', False)}`",
        f"- started {report.get('started_at', '?')}, completed {report.get('completed_at', '?')}",
        "",
        "| measure | count |",
        "|---|---|",
    ]
    lines += [f"| {key.replace('_', ' ')} | {value} |" for key, value in numbers.items()]
    lines.append("")
    if report.get("failures"):
        lines.append("Failures (a fetch failure is never reported as unchanged):")
        for item in report["failures"]:
            lines.append(
                f"- `{item.get('source_id')}`: {item.get('status')} — {item.get('class', item.get('detail', ''))}"
            )
        lines.append("")
    if engine_exit is not None:
        lines.append(f"- engine exit code: `{engine_exit}` (0 clean, 1 source failure, 3 engine defect)")
    if validate_exit is not None:
        note = (
            "repository contracts current"
            if validate_exit == 0
            else "validation failed — expected when a pinned source changed; a human re-review is required before merge"
        )
        lines.append(f"- `dk.py validate` exit code: `{validate_exit}` — {note}")
    lines.append(f"- trusted knowledge mutations: `{len(report.get('trusted_knowledge_mutations', []))}`")
    lines.append(f"- persistence: `{persistence}`" + (f" on `{branch}`" if branch else ""))
    lines.append("")
    lines.append(
        "Source changes and discovery signals are review work. Nothing here becomes "
        "trusted knowledge without a human edit in a separately reviewed commit."
    )
    return "\n".join(lines) + "\n"


def commit_message(operation: str, report: dict) -> str:
    spec = OPERATIONS[operation]
    numbers = counts(operation, report)
    if operation == "acquisition":
        subject = (
            f"Scheduled acquisition: {numbers['changed']} changed, "
            f"{numbers['unchanged']} unchanged, {numbers['failures']} failed"
        )
    else:
        subject = (
            f"Scheduled discovery: {numbers['signals_created']} new signal(s), "
            f"{numbers['signals_updated']} updated, {numbers['failures']} failed"
        )
    body = [
        subject,
        "",
        f"Automated output of `{spec['command']}` (run {report.get('run_id', '?')}).",
        "Source state, immutable snapshots and review candidates only, plus the",
        "derived public artifacts regenerated from them. No trusted knowledge was",
        "changed; review is required before merge.",
    ]
    return "\n".join(body) + "\n"


def pull_request_body(
    operation: str,
    report: dict,
    *,
    validate_exit: int | None,
    engine_exit: int | None,
) -> str:
    spec = OPERATIONS[operation]
    parts = [
        summary_markdown(
            operation,
            report,
            persistence="pending",
            validate_exit=validate_exit,
            engine_exit=engine_exit,
            branch=spec["branch"],
        ),
        "### What this pull request may contain",
        "",
        "Only these paths, enforced by `scripts/dk_automation.py check-paths` before anything is committed:",
        "",
    ]
    parts += [f"- `{path}`" for path in allowed_paths(operation)]
    parts += [
        "",
        "### Review",
        "",
        "- This branch is rebuilt from `main` by every scheduled run and force-pushed with a lease; "
        "review it here rather than committing to it.",
        "- Merge requires the branch ruleset: every required check green, no auto-merge, no bypass.",
        "- GitHub does not start `push`/`pull_request` workflows for changes made with the workflow token. "
        "To run the required checks on this branch, use **Update branch** or close and reopen the pull request.",
        "- A red `dk.py validate` means a pinned source changed and its reviewed context must be "
        "re-normalized by a human in a separate commit; that is the trust boundary working.",
        "",
    ]
    return "\n".join(parts)


# --- CLI ------------------------------------------------------------------------


def _load_report(path: str) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    paths = sub.add_parser("paths", help="print the persistence allow-list, one path per line")
    paths.add_argument("--operation", choices=sorted(OPERATIONS), required=True)

    check = sub.add_parser(
        "check-paths",
        help="read `git status --porcelain -z` on stdin; exit 1 if any changed path is outside the allow-list",
    )
    check.add_argument("--operation", choices=sorted(OPERATIONS), required=True)

    for name, help_text in (
        ("summary", "render the run summary (Markdown) from the engine report"),
        ("pr-body", "render the pull request body from the engine report"),
        ("commit-message", "render the automation commit message from the engine report"),
    ):
        render = sub.add_parser(name, help=help_text)
        render.add_argument("--operation", choices=sorted(OPERATIONS), required=True)
        render.add_argument("--report", required=True)
        render.add_argument("--persistence", choices=PERSISTENCE_OUTCOMES, default="pending")
        render.add_argument("--validate-exit", type=int, default=None)
        render.add_argument("--engine-exit", type=int, default=None)

    args = parser.parse_args(argv)
    try:
        if args.command == "paths":
            print("\n".join(allowed_paths(args.operation)))
            return 0
        if args.command == "check-paths":
            changed = parse_porcelain(sys.stdin.buffer.read())
            outcome = check_paths(args.operation, changed)
            print(f"AUTOMATION_CHANGED_PATHS={len(outcome['allowed'])}")
            print("AUTOMATION_FORBIDDEN_PATHS=0")
            return 0
        report = _load_report(args.report)
        if args.command == "summary":
            sys.stdout.write(
                summary_markdown(
                    args.operation,
                    report,
                    persistence=args.persistence,
                    validate_exit=args.validate_exit,
                    engine_exit=args.engine_exit,
                    branch=OPERATIONS[args.operation]["branch"],
                )
            )
        elif args.command == "pr-body":
            sys.stdout.write(
                pull_request_body(
                    args.operation,
                    report,
                    validate_exit=args.validate_exit,
                    engine_exit=args.engine_exit,
                )
            )
        elif args.command == "commit-message":
            sys.stdout.write(commit_message(args.operation, report))
        return 0
    except AutomationBoundaryError as exc:
        print(f"AUTOMATION_BOUNDARY_VIOLATION: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
