#!/usr/bin/env python3
"""What the public website is allowed to say, and what it must not imply.

A website is a different risk from a CLI. Nobody installs it, nobody reads its
help text, and a page is often the only thing a developer ever sees. Two
failures matter more here than anywhere else in this repository.

The first is a second opinion. If the site interpreted canonical records itself,
it could disagree with the command line and nothing would notice. The tests
below hold the pipeline in one direction — records, released query layer, public
dataset, pages — and prove the renderer cannot see past the dataset.

The second is publishing what was never meant to be public. Project evidence,
findings, discovery signals and anything carrying a local path or a project
name are excluded by name, and the generated bytes are scanned rather than
trusted.

Everything here is hermetic: canonical local records only, no network, and the
stale-guard fixture works on a copy so no test can leave the repository dirty.
"""

from __future__ import annotations

import ast
import html
import html.parser
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import dk_core
import dk_public as P
import dk_query as Q
import dk_site_render as R


ROOT = dk_core.ROOT
CLI = ROOT / "scripts" / "dk.py"
DIST = ROOT / "public-site" / "dist"
FIXED_BUILD = "2026-09-09T00:00:00Z"


def flat(text: str) -> str:
    """Collapse whitespace so a phrase assertion survives HTML wrapping."""
    return " ".join(text.split())


def build_site(dataset: dict) -> dict[str, str]:
    """Render with fixed inputs so two calls are comparable."""
    root = ROOT / "public-site"
    editorial = {
        path.stem: path.read_text(encoding="utf-8").rstrip("\n")
        for path in sorted((root / "content").glob("*.html"))
    }
    assets = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted((root / "assets").iterdir())
        if path.is_file()
    }
    import dk as cli

    commands = [{"command": name, "help": ""} for name in cli.commands_for("community")]
    return R.render_site(
        dataset,
        editorial=editorial,
        assets=assets,
        commands=commands,
        built_at=FIXED_BUILD,
        today_ordinal=739_500,
        parse_day=lambda stamp: 739_400,
        commit="fixed",
    )


DATASET = P.build_dataset(ROOT)
MANIFEST = DATASET[P.MANIFEST_FILE]
SITE = build_site(DATASET)
PAGES = {name: text for name, text in SITE.items() if name.endswith(".html")}


# --- architecture -------------------------------------------------------------

export_source = (ROOT / "scripts" / "dk_public.py").read_text(encoding="utf-8")
render_source = (ROOT / "scripts" / "dk_site_render.py").read_text(encoding="utf-8")

# The export reaches canonical records only through the released query layer.
assert "import dk_query" in export_source
for forbidden in ("json.load", "yaml", "glob(", "os.walk", "rglob"):
    assert forbidden not in export_source, forbidden
print("PUBLIC_SITE_REUSES_RELEASED_QUERY_LAYER=PASS")

# The renderer cannot reach canonical records at all: no query layer, no core,
# no repository root. It is structurally incapable of a second opinion.
# Parsed, not grepped: the docstring names the modules the renderer is kept away
# from, and prose about a boundary is not a breach of it.
render_imports = set()
for node in ast.walk(ast.parse(render_source)):
    if isinstance(node, ast.Import):
        render_imports.update(alias.name.split(".")[0] for alias in node.names)
    elif isinstance(node, ast.ImportFrom):
        render_imports.add((node.module or "").split(".")[0])
assert render_imports <= {"__future__", "html", "json", "pathlib", "typing"}, render_imports
for forbidden in ("open(", "read_text", "read_bytes", "Path(", "ROOT"):
    assert forbidden not in render_source, forbidden
assert "def render_site(" in render_source
print("PUBLIC_SITE_ARCHITECTURE_MINIMAL_AND_AUDITABLE=PASS")

# The export decides nothing about Drupal: no version comparison, no severity,
# no applicability, no ranking of its own.
for forbidden in (
    "def score_record", "def evaluate", "def applies", "severity",
    "affected_versions =", "def compare_version", "cvss",
):
    assert forbidden not in export_source.lower(), forbidden
# Ranking is imported from the released layer, not rewritten here.
assert "query.score_record(" in export_source
assert "def score" not in export_source
print("PUBLIC_EXPORT_CONTAINS_NO_SECOND_SEMANTIC_ENGINE=PASS")

# No HTTP server, no request handling, no route dispatch: this is a build.
for forbidden in ("flask", "fastapi", "django", "wsgi", "asgi", "@app.route", "request."):
    assert forbidden not in (export_source + render_source).lower(), forbidden
assert "api_status" in MANIFEST and "not a supported API contract" in MANIFEST["api_status"]
print("PUBLIC_SITE_DOES_NOT_PREEMPT_PUBLIC_API=PASS")

# No SPA framework, no bundler, no client-side routing.
search_js = (ROOT / "public-site" / "assets" / "search.js").read_text(encoding="utf-8")
for forbidden in ("react", "vue", "angular", "svelte", "import ", "require(", "webpack"):
    assert forbidden not in search_js.lower(), forbidden
assert len(PAGES) > 300, "record pages are generated, not client-rendered"
# Every domain page is readable with scripts off: only search references a script.
scripted = [name for name, text in PAGES.items() if "<script" in text]
assert scripted == ["search/index.html"], scripted
print("PUBLIC_SITE_AVOIDS_UNNECESSARY_CLIENT_COMPLEXITY=PASS")


# --- dataset contract ---------------------------------------------------------

for key in (
    "dataset_schema_version", "dk_version", "query_interface_version",
    "generated_from_release", "dataset_id", "domains", "record_counts",
    "source_freshness_summary", "trust_classes", "routes", "excluded_domains",
):
    assert key in MANIFEST, key
assert MANIFEST["dk_version"] == (ROOT / "VERSION").read_text(encoding="utf-8").strip()
assert MANIFEST["query_interface_version"] == Q.QUERY_INTERFACE_VERSION
assert MANIFEST["page_count"] == len(MANIFEST["routes"]) == len(PAGES)
# Volatile build metadata is separate from semantic dataset identity.
assert "generated_at" not in MANIFEST and "built_at" not in MANIFEST
build_info = json.loads(SITE["build-info.json"])
for key in ("dk_version", "dataset_id", "commit", "built_at", "page_count", "record_counts"):
    assert key in build_info, key
print("PUBLIC_DATASET_MANIFEST_MACHINE_READABLE=PASS")
print("PUBLIC_BUILD_MANIFEST_PRESENT=PASS")

# Identity is content-addressed and reproducible from the same canonical state.
again = P.build_dataset(ROOT)
assert again[P.MANIFEST_FILE]["dataset_id"] == MANIFEST["dataset_id"]
assert Q.stable_json(again) == Q.stable_json(DATASET)
assert MANIFEST["dataset_id"].startswith("dataset:")
print("PUBLIC_DATASET_IDENTITY_DETERMINISTIC=PASS")


# --- fixture A: reviewed knowledge is published and labelled -------------------

knowledge = DATASET[P.DOMAIN_FILE[Q.D_KNOWLEDGE]]
assert knowledge["record_count"] == 11
for record in knowledge["records"]:
    assert record["trust"]["class"] == "reviewed_drupal_knowledge"
    assert record["trust"]["trusted_knowledge"] is True
    assert record["trust"]["review_status"] == "reviewed"
    page = PAGES[R.output_path(record["route"])]
    assert "Reviewed Drupal Knowledge" in page
    # Scope, authority, provenance and limitations all reach the page.
    assert "What makes it authoritative" in flat(page)
    assert "What is not known" in flat(page)
    assert "Provenance" in flat(page)
print("FIXTURE_A_REVIEWED_KNOWLEDGE_PUBLISHED=PASS")
print("PUBLIC_TRUSTED_KNOWLEDGE_ONLY_REVIEWED=PASS")


# --- fixture B: unreviewed material is not published as knowledge --------------

on_disk = dk_core.load_knowledge_records(ROOT)
reviewed = [record for record in on_disk if record["review_status"] == "reviewed"]
assert len(knowledge["records"]) == len(reviewed)
unreviewed_ids = {
    record["id"] for record in on_disk if record["review_status"] != "reviewed"
}
published_ids = {record["id"] for record in knowledge["records"]}
assert not (unreviewed_ids & published_ids)
blob = Q.stable_json(DATASET)
for identifier in unreviewed_ids:
    assert identifier not in blob, identifier
# Generalization proposals awaiting review are not a published domain at all.
proposals = list(dk_core.iter_json_files(ROOT / "cases" / "generalizations"))
for path in proposals:
    proposal = dk_core.read_json(path)
    assert proposal.get("id", "\x00") not in blob
assert Q.D_KNOWLEDGE in P.PUBLIC_DOMAINS
assert not any(domain.startswith("generalization") for domain in P.PUBLIC_DOMAINS)
print("FIXTURE_B_UNREVIEWED_NOT_PUBLISHED=PASS")
print("UNREVIEWED_GENERALIZATIONS_NOT_PUBLIC_KNOWLEDGE=PASS")


# --- fixture C: a security advisory keeps every authoritative field -----------

security = DATASET[P.DOMAIN_FILE[Q.D_ADVISORY]]
advisory = next(r for r in security["records"] if r["id"] == "SA-CORE-2025-001")
canonical = dk_core.read_json(ROOT / "security" / "advisories" / "SA-CORE-2025-001.json")
assert advisory["route"] == "/security/SA-CORE-2025-001/"
detail = advisory["detail"]
assert detail["affected_versions"] == canonical["affected_versions"]["source_value"]
assert detail["fixed_in"] == canonical["fixed_in"]["versions"]
assert detail["risk_vector"] == canonical["severity"]["risk_vector"]
assert detail["cves"] == canonical["cves"]["identifiers"]
assert detail["kind"] == canonical["advisory"]["kind"]
assert detail["remediation_state"] == canonical["remediation"]["state"]
# Nothing is scored, invented or recomputed here.
assert detail["scored_by_drupal_knowledge"] is False
assert detail["remediation_authored_by_drupal_knowledge"] is False
assert "cvss" not in Q.stable_json(advisory).lower()
page = PAGES["security/SA-CORE-2025-001/index.html"]
for expected in (
    canonical["affected_versions"]["source_value"].replace(">", "&gt;").replace("<", "&lt;"),
    canonical["severity"]["risk_vector"],
    canonical["cves"]["identifiers"][0],
    "https://www.drupal.org/sa-core-2025-001",
    "Authoritative Drupal Source Record",
):
    assert expected in flat(page), expected
for version in canonical["fixed_in"]["versions"]:
    assert version in flat(page), version
print("FIXTURE_C_ADVISORY_ROUTE_AND_FIELDS=PASS")
print("PUBLIC_SECURITY_PRESERVES_AUTHORITATIVE_FIELDS=PASS")

# Advisory routes are the advisory's own identifier, not a filesystem path.
for record in security["records"]:
    assert record["route"] == f"/security/{record['id']}/"
for domain in P.PUBLIC_DOMAINS:
    for record in DATASET[P.DOMAIN_FILE[domain]]["records"]:
        assert record["id"] in record["route"], record["id"]
        assert "/Users/" not in record["route"] and ".json" not in record["route"]
print("PUBLIC_ADVISORY_ROUTES_STABLE=PASS")
print("PUBLIC_ROUTES_USE_CANONICAL_IDENTITIES=PASS")


# --- fixture D & E: search finds a CVE and an API symbol ----------------------

rows = DATASET[P.SEARCH_INDEX_FILE]["rows"]
cve = canonical["cves"]["identifiers"][0]
hits = P.search(cve, rows)
assert hits and hits[0]["id"] == "SA-CORE-2025-001"
assert hits[0]["rank"] == Q.RANK_EXACT_FIELD
print("FIXTURE_D_CVE_FINDS_ADVISORY=PASS")

symbol = P.search("file_create_url", rows)
assert symbol and symbol[0]["domain"] == Q.D_API_LIFECYCLE
assert symbol[0]["rank"] == Q.RANK_EXACT_ID
assert symbol[0]["route"].startswith("/api/")
change = P.search("user_role_grant_permissions", rows)
assert any(hit["domain"] == Q.D_CHANGE_RECORD for hit in change)
print("FIXTURE_E_API_SYMBOL_FINDS_RECORD=PASS")

# Module and project names, and knowledge text, are searchable too.
assert any(hit["domain"] == Q.D_ADVISORY for hit in P.search("entity_pdf", rows))
assert any(hit["domain"] == Q.D_KNOWLEDGE for hit in P.search("coding standards", rows))
assert P.search("SA-CORE-2025-001", rows)[0]["rank"] == Q.RANK_EXACT_ID
print("FIXTURE_N_EXACT_IDENTIFIER_RANKS_FIRST=PASS")

# The site ranks with the released scorer itself, not a copy of it.
for term in ("SA-CORE-2025-001", cve, "file_create_url", "views", "entity_pdf"):
    cli_hits = [
        item["id"]
        for item in Q.search(term, ROOT, limit=50)["results"]
        if item["domain"] in P.PUBLIC_DOMAINS
    ]
    site_hits = [hit["id"] for hit in P.search(term, rows, limit=50)]
    assert cli_hits == site_hits, (term, cli_hits[:5], site_hits[:5])
assert P.search("Views", rows) == P.search("views", rows)
print("PUBLIC_SEARCH_REUSES_COMMUNITY_QUERY_SEMANTICS=PASS")
print("PUBLIC_SEARCH_DETERMINISTIC=PASS")

# The browser gets the released bands, and the script mirrors the same order.
bands = DATASET[P.SEARCH_INDEX_FILE]["ranking"]
assert bands == {
    "exact_id": Q.RANK_EXACT_ID,
    "exact_field": Q.RANK_EXACT_FIELD,
    "prefix_id": Q.RANK_PREFIX_ID,
    "exact_token": Q.RANK_EXACT_TOKEN,
    "title_substring": Q.RANK_TITLE_SUBSTRING,
    "body_substring": Q.RANK_BODY_SUBSTRING,
}
order = [
    search_js.index(f"bands.{name}")
    for name in ("exact_id", "exact_field", "prefix_id", "exact_token", "title_substring", "body_substring")
]
assert order == sorted(order), "the script must test the bands in the released order"
assert "bands." in search_js and "1000" not in search_js, "bands must not be hard-coded"

# The index carries only what a result list needs.
allowed = {"id", "domain", "route", "title", "summary", "trust_class", "identity", "structured", "body"}
for row in rows:
    assert set(row) == allowed, set(row) ^ allowed
    assert "provenance" not in row and "detail" not in row and "explanation" not in row
assert len(Q.stable_json(rows)) < len(Q.stable_json(DATASET)) // 3
print("PUBLIC_SEARCH_INDEX_MINIMIZED=PASS")

# The browser downloads the index and nothing else from the dataset.
shipped = {name for name in SITE if name.endswith(".json")}
assert shipped == {"search-index.json", "manifest.json", "build-info.json"}, shipped
for name in P.DOMAIN_FILE.values():
    assert name not in SITE
print("PUBLIC_SITE_DOES_NOT_SHIP_INTERNAL_DATASET=PASS")


# --- fixture F: discovery signals are not published ---------------------------

assert Q.D_DISCOVERY_SIGNAL not in P.PUBLIC_DOMAINS
assert Q.D_DISCOVERY_SIGNAL in P.EXCLUDED_DOMAINS
signals = Q.list_domain(Q.D_DISCOVERY_SIGNAL, ROOT)["results"]
assert signals, "the fixture is meaningless if the repository holds no signals"
site_blob = "\n".join(SITE.values())
for signal in signals:
    assert signal["id"] not in site_blob, signal["id"]
    assert signal["id"] not in blob
# The absence is stated rather than silent.
trust_page = PAGES["trust-model/index.html"]
assert "discovery_signal" in trust_page
assert "publishes none of them" in flat(trust_page)
assert "Untrusted Discovery Signal" in trust_page
print("FIXTURE_F_DISCOVERY_NOT_PUBLISHED=PASS")
print("PUBLIC_SITE_DOES_NOT_PRESENT_DISCOVERY_AS_TRUTH=PASS")

# Nothing untrusted is indexable, because nothing untrusted has a page. Search
# results and the error page carry noindex because they are not content.
robots = SITE["robots.txt"]
assert "Disallow: /search/" in robots
assert 'content="noindex"' in PAGES["search/index.html"]
assert 'content="noindex"' in PAGES["404.html"]
indexable = [name for name, text in PAGES.items() if 'content="noindex"' not in text]
for name in indexable:
    assert "Untrusted Discovery Signal</span>" not in PAGES[name] or name == "trust-model/index.html"
print("PUBLIC_INDEXING_RESPECTS_TRUST_BOUNDARY=PASS")


# --- fixture G: the solved case is privacy-safe and context-bounded -----------

cases = DATASET[P.DOMAIN_FILE[Q.D_SOLVED_CASE]]
assert cases["record_count"] == 1, "report the real number, do not weaken the filter"
case = cases["records"][0]
raw_case = dk_core.load_solved_cases(ROOT)[0]
assert case["trust"]["class"] == "proven_case_context_only"
assert case["detail"]["project_identity_disclosed"] is False
# The useful parts survive: problem, cause, fix, verification, limitations.
for key in ("problem", "root_cause", "solution", "verification", "limitations", "conditions"):
    assert case["detail"][key], key
# The identifying parts do not.
case_text = Q.stable_json(case)
for private in ("project_fingerprint", "revision_fingerprint", "captured_by", "environment"):
    assert private not in case_text, private
case_page = PAGES[R.output_path(case["route"])]
assert "Internal Proven Solved Case" in case_page
assert "not universal drupal truth" in flat(case_page).lower()
assert "Widening it requires review" in flat(case_page)
print("FIXTURE_G_SOLVED_CASE_PRIVACY_AND_CONTEXT=PASS")
print("PUBLIC_SOLVED_CASE_PRIVACY_PRESERVED=PASS")


# --- fixture H: staleness is visible and not alarmist -------------------------

sources = DATASET[P.SOURCES_FILE]["sources"]
assert len(sources) == 34
stale_source = dict(sources[0])
stale_source["check_cadence_days"] = 1
freshness = R.freshness_of(stale_source, 739_500, lambda stamp: 739_000)
assert freshness["stale"] is True
assert freshness["state"] == "past its check cadence"
rendered = R.source_page(stale_source, MANIFEST, freshness, FIXED_BUILD)
assert "past its check cadence" in flat(rendered)
assert "Last successfully observed" in flat(rendered)
# Stale is not wrong, and the page says so in those words.
assert "not a source known to be wrong" in flat(rendered)
for alarm in ("incorrect", "invalid", "untrustworthy", "expired"):
    assert alarm not in rendered.lower(), alarm
print("FIXTURE_H_STALENESS_VISIBLE_NOT_ALARMIST=PASS")
print("PUBLIC_STALENESS_VISIBLE_AND_NON_ALARMIST=PASS")

# The source directory publishes what is safe and nothing operational.
source_text = Q.stable_json(sources)
# Credential *artifacts*, not the word "auth": "authoritative" is the trust tier
# every registered source declares and it belongs in the directory.
for private in (
    "credential", "authorization", "auth_token", "api_key", "bearer",
    "cookie", "local_path", "snapshot_path", "request_headers", "password",
):
    assert private not in source_text.lower(), private
for entry in sources:
    assert entry["url"].startswith("http")
    assert set(entry) == {
        "id", "route", "title", "url", "trust", "category", "role", "lifecycle",
        "check_cadence_days", "baselined", "last_observed_at", "snapshot_sha256",
    }
print("PUBLIC_SOURCE_DIRECTORY_SAFE=PASS")


# --- fixture I: provenance leads from a record to its source ------------------

step = advisory["provenance"][0]
assert step["source_id"] and step["snapshot_sha256"].startswith("sha256:")
assert step["source_url"].startswith("https://")
source_route = next(s["route"] for s in sources if s["id"] == step["source_id"])
assert f'href="{source_route}"' in page
source_page_html = PAGES[R.output_path(source_route)]
registered = next(s for s in dk_core.load_sources(ROOT) if s["id"] == step["source_id"])
assert registered["url"] in source_page_html
# And the snapshot the chain names is real and addressable by its own hash.
snapshot = dk_core.require_snapshot(ROOT, step["source_id"], step["snapshot_sha256"])
assert snapshot.is_file()
# No provenance step anywhere publishes where a snapshot lives on disk.
for domain in P.PUBLIC_DOMAINS:
    for record in DATASET[P.DOMAIN_FILE[domain]]["records"]:
        for entry in record["provenance"]:
            assert set(entry) <= {
                "channel", "source_id", "source_url", "snapshot_sha256",
                "locator", "case_id", "rule_id",
            }, set(entry)
print("FIXTURE_I_PROVENANCE_NAVIGABLE=PASS")
print("PUBLIC_PROVENANCE_NAVIGABLE=PASS")


# --- fixture J: private paths are rejected, not merely filtered ---------------

for leaked in (
    {"note": "/Users/someone/sites/client"},
    {"note": "/home/deploy/app"},
    {"contact": "reviewer@example.com"},
    {"settings": "hash_salt = 'abc'"},
):
    try:
        P.assert_public_safe("fixture", leaked)
    except P.PublicExportDefect:
        continue
    raise AssertionError(f"the export accepted {leaked}")
print("FIXTURE_J_PRIVATE_PATH_REJECTED=PASS")

# And the real generated output carries none of it.
generated = "\n".join(SITE.values()) + Q.stable_json(DATASET)
for pattern, description in P.PRIVATE_PATTERNS:
    found = pattern.search(generated)
    # The repository's own public URLs are the only addresses that may appear.
    assert not found, f"{description}: {found.group(0) if found else ''}"
for private in ("/Users/", "/home/", "C:\\Users", "PhpstormProjects", ".git/"):
    assert private not in generated, private
print("PUBLIC_BUILD_PRIVACY_SCAN_PASS=PASS")

# Project-scoped domains are excluded by name, with a reason, and nothing they
# would produce appears anywhere.
for domain in (
    Q.D_PROJECT_EVIDENCE, Q.D_FINDING, Q.D_IMPLEMENTATION_FINDING,
    Q.D_MIGRATION_WORK, Q.D_UPGRADE_ASSESSMENT, Q.D_REMEDIATION_PLAN,
):
    assert domain not in P.PUBLIC_DOMAINS
    assert P.EXCLUDED_DOMAINS[domain]
assert set(P.PUBLIC_DOMAINS) | set(P.EXCLUDED_DOMAINS) == set(Q.DOMAINS)
for marker in ("evidence-set.", "implementation-evaluation.", "upgrade-assessment.", "migration-analysis."):
    assert marker not in generated, marker
print("PROJECT_PRIVATE_EVIDENCE_NOT_PUBLICLY_EXPORTED=PASS")

# Nothing internal reaches the build: no repository state, no maintainer surface.
for internal in (
    "sources/state/", "discovery/candidates/", "discovery/review/",
    "exchange/", "feedback/", "evidence/projects/", "scripts/test_",
):
    assert internal not in generated, internal
for maintainer in ("dk acquire", "dk discover", "dk review-candidates", "dk signal-review"):
    assert maintainer not in generated, maintainer
print("PUBLIC_BUILD_EXCLUDES_INTERNAL_ARTIFACTS=PASS")


# --- fixture K: two builds agree ----------------------------------------------

second_site = build_site(P.build_dataset(ROOT))
assert second_site == SITE
assert sorted(second_site) == sorted(SITE)
print("FIXTURE_K_REPEATED_BUILD_IDENTICAL=PASS")
print("PUBLIC_SITE_BUILD_DETERMINISTIC=PASS")


# --- fixture L: canonical data changed without a rebuild is detected ----------

with tempfile.TemporaryDirectory() as tmp:
    copy = Path(tmp) / "repo"
    shutil.copytree(
        ROOT,
        copy,
        ignore=shutil.ignore_patterns(
            ".git", "dist", "__pycache__", ".venv", "evidence", "exchange", "feedback"
        ),
    )
    # A freshly copied repository is current.
    assert P.validate_public_dataset(copy) == ["PUBLIC_DATASET_CURRENT=PASS"]

    # Change one canonical record and publish nothing.
    target = copy / "security" / "advisories" / "SA-CORE-2025-001.json"
    mutated = dk_core.read_json(target)
    mutated["advisory"]["vulnerability_type"] = "Changed without republishing"
    target.write_text(json.dumps(mutated, indent=2) + "\n", encoding="utf-8")

    try:
        P.validate_public_dataset(copy)
    except dk_core.ValidationError as exc:
        assert "stale" in str(exc)
        assert "public-site/dataset" in str(exc)
        assert "public-site build" in str(exc)
    else:
        raise AssertionError("a changed canonical record left the dataset looking current")

    # Rebuilding makes it current again, and the identity has moved.
    before = MANIFEST["dataset_id"]
    P.write_dataset(copy)
    assert P.validate_public_dataset(copy) == ["PUBLIC_DATASET_CURRENT=PASS"]
    assert P.build_dataset(copy)[P.MANIFEST_FILE]["dataset_id"] != before
print("FIXTURE_L_STALE_GENERATION_DETECTED=PASS")
print("PUBLIC_SITE_STALE_GENERATION_DETECTED=PASS")
print("PUBLIC_CONTENT_GENERATED_FROM_CANONICAL_DATA=PASS")


# --- fixture M: the CLI and the website say the same thing --------------------

for identifier in ("SA-CORE-2025-001", "api-lifecycle.3f79df0f90cc1c83", "change-record.3348027"):
    cli_payload = json.loads(
        subprocess.run(
            [sys.executable, str(CLI), "explain", identifier, "--json"],
            capture_output=True, text=True, check=True,
        ).stdout
    )
    cli_item = cli_payload["results"][0]
    published = next(
        record
        for domain in P.PUBLIC_DOMAINS
        for record in DATASET[P.DOMAIN_FILE[domain]]["records"]
        if record["id"] == identifier
    )
    assert published["domain"] == cli_item["domain"]
    assert published["title"] == cli_item["title"]
    assert published["summary"] == cli_item["summary"]
    assert published["trust"] == cli_item["trust"]
    assert published["detail"] == cli_item["detail"]
    assert published["unknowns"] == cli_item["unknowns"]
    assert published["explanation"] == cli_item["explanation"]
    # And the page renders those same values rather than its own.
    rendered_page = PAGES[R.output_path(published["route"])]
    assert html.escape(cli_item["title"], quote=True) in flat(rendered_page)
    assert html.escape(cli_item["trust"]["explanation"], quote=True) in flat(rendered_page)
print("FIXTURE_M_CLI_AND_SITE_AGREE=PASS")
print("CLI_AND_WEBSITE_SEMANTIC_PARITY=PASS")


# --- trust rendering ----------------------------------------------------------

# Every published trust class has a public badge, and the badge is words.
for domain in P.PUBLIC_DOMAINS:
    trust_class = Q.DOMAIN_TRUST_CLASS[domain]
    assert R.TRUST_BADGE[trust_class]
    index_html = PAGES[R.output_path(P.index_route(domain))]
    assert R.TRUST_BADGE[trust_class] in index_html
assert set(R.TRUST_BADGE) == set(Q.TRUST_CLASSES)
# Colour is reinforcement only: every badge carries its meaning as text.
css = (ROOT / "public-site" / "assets" / "site.css").read_text(encoding="utf-8")
for trust_class in Q.TRUST_CLASSES:
    if trust_class in {Q.DOMAIN_TRUST_CLASS[d] for d in P.PUBLIC_DOMAINS}:
        assert f"badge--{trust_class}" in css
for name, text in PAGES.items():
    for match in re.findall(r'<span class="badge[^"]*">([^<]*)</span>', text):
        assert match.strip(), f"an empty badge on {name}"
print("PUBLIC_TRUST_LABELS_VISIBLE=PASS")

# The trust model page explains every class and every refusal.
for term in (
    "authoritative", "reviewed", "source-derived", "project evidence",
    "finding", "solved case", "discovery signal",
):
    assert term.lower() in flat(trust_page).lower(), term
for refusal in ("not observed", "unknown", "secure", "compliant"):
    assert refusal.lower() in flat(trust_page).lower(), refusal
assert "Trusted knowledge" in trust_page
trusted_rows = re.findall(r"<td>(yes|no)</td>\s*<td>", trust_page)
assert trusted_rows.count("yes") == 1, "exactly one class is trusted knowledge"
print("PUBLIC_TRUST_MODEL_DOCUMENTED=PASS")


# --- home page and information architecture -----------------------------------

home = PAGES["index.html"]
for expected in (
    "What it is", "What it does not claim", "How to use it",
    "dk project", "/search/", "/cli/",
):
    assert expected in flat(home), expected
for marketing in ("AI-powered", "artificial intelligence", "guaranteed", "complete coverage"):
    assert marketing.lower() not in flat(home).lower(), marketing
for internal in ("acquisition engine", "corroboration dossier", "applicability resolver"):
    assert internal.lower() not in flat(home).lower(), internal
assert "not comprehensive" in flat(home).lower()
print("PUBLIC_HOME_PAGE_DEVELOPER_ORIENTED=PASS")

nav_routes = [href for href, _ in R.NAV]
assert nav_routes[:6] == [P.index_route(domain) for domain in P.PUBLIC_DOMAINS]
for maintainer_word in ("Acquire", "Review candidates", "Discovery", "Promote"):
    assert maintainer_word not in home[: home.index("</header>")]
assert "/sources/" in nav_routes and "/trust-model/" in nav_routes and "/cli/" in nav_routes
print("PUBLIC_INFORMATION_ARCHITECTURE_COMMUNITY_ORIENTED=PASS")


# --- CLI page truthfulness ----------------------------------------------------

import dk as cli_module

cli_page_html = PAGES["cli/index.html"]
named = set(re.findall(r"\bdk ([a-z][a-z0-9-]+)", re.sub(r"<[^>]+>", " ", cli_page_html)))
parser = cli_module.build_parser()
import argparse as _argparse

registered = set(
    next(a for a in parser._actions if isinstance(a, _argparse._SubParsersAction)).choices
)
unknown = sorted(name for name in named if name not in registered)
assert not unknown, f"the CLI page names commands that do not exist: {unknown}"
for command in ("status", "project", "search", "explain", "provenance"):
    assert f"dk {command}" in flat(cli_page_html), command
print("PUBLIC_CLI_DOCUMENTATION_MATCHES_RELEASED_CLI=PASS")

about = PAGES["about/index.html"]
assert "github.com/zarabatana/drupal-knowledge" in cli_page_html
assert "git clone" in cli_page_html
for fiction in ("composer require", "npm install", "brew install", "pip install", "apt install"):
    assert fiction not in flat(cli_page_html + " " + about).lower(), fiction
assert "no Composer package" in flat(cli_page_html)
print("PUBLIC_INSTALLATION_GUIDANCE_TRUTHFUL=PASS")

# The site has no mechanism to accept anything: the only form on the whole site
# is the search box, and it is a GET against a static page.
forms = {name: re.findall(r"<form[^>]*>", text) for name, text in PAGES.items()}
assert {name for name, found in forms.items() if found} == {"search/index.html"}, forms
assert 'method="get"' in PAGES["search/index.html"]
for mechanism in ('<input type="file"', "enctype=", "multipart/form-data", "method=\"post\"",
                  "sign in", "log in", "create an account", "<textarea"):
    for name, text in PAGES.items():
        assert mechanism.lower() not in text.lower(), (name, mechanism)
# And it says so, which is why the word appears at all.
assert "You cannot upload a project" in flat(about)
print("PUBLIC_SITE_HAS_NO_PROJECT_UPLOAD_OR_ANALYSIS=PASS")


# --- cross-links --------------------------------------------------------------

all_routes = {entry["route"] for entry in MANIFEST["routes"]}
for domain in P.PUBLIC_DOMAINS:
    for record in DATASET[P.DOMAIN_FILE[domain]]["records"]:
        for entry in record.get("related", []):
            assert entry["route"] in all_routes, entry
            assert entry["relation"] in R.RELATION_LABEL, entry["relation"]
# Every advisory sibling link is the project machine name both advisories
# declare, never a resemblance between their titles.
for record in DATASET[P.DOMAIN_FILE[Q.D_ADVISORY]]["records"]:
    for entry in record.get("related", []):
        if entry["relation"] != "same_drupal_project":
            continue
        sibling = next(
            r for r in DATASET[P.DOMAIN_FILE[Q.D_ADVISORY]]["records"]
            if r["route"] == entry["route"]
        )
        assert sibling["detail"]["project"] == record["detail"]["project"]

# Symbol linking is exact string identity on a field both records publish. No
# lifecycle record in this release shares a symbol with a change record, so the
# relation is currently empty against real data and is proven on a fixture
# rather than left unexercised.
fixture = {
    Q.D_API_LIFECYCLE: [
        {"id": "a1", "domain": Q.D_API_LIFECYCLE, "route": "/api/a1/", "title": "node_load",
         "detail": {"symbol": "node_load"}, "provenance": []},
        {"id": "a2", "domain": Q.D_API_LIFECYCLE, "route": "/api/a2/", "title": "node_loader",
         "detail": {"symbol": "node_loader"}, "provenance": []},
    ],
    Q.D_CHANGE_RECORD: [
        {"id": "c1", "domain": Q.D_CHANGE_RECORD, "route": "/change-records/c1/",
         "title": "node_load is deprecated", "detail": {"symbols": ["node_load"]},
         "provenance": []},
    ],
}
P.link_related(fixture, [])
linked = [e for e in fixture[Q.D_API_LIFECYCLE][0]["related"]]
assert [e["relation"] for e in linked] == ["described_by_change_record"]
assert linked[0]["route"] == "/change-records/c1/"
# node_loader contains node_load as a substring and is still not related.
assert fixture[Q.D_API_LIFECYCLE][1]["related"] == []
assert [e["relation"] for e in fixture[Q.D_CHANGE_RECORD][0]["related"]] == ["names_this_symbol"]

for fuzzy in ("difflib", "SequenceMatcher", "startswith", "in title", "fuzzy"):
    assert fuzzy not in export_source.replace("value.lower().startswith", ""), fuzzy
print("PUBLIC_CROSS_LINKS_CANONICAL_ONLY=PASS")


# --- error output -------------------------------------------------------------

missing = PAGES["404.html"]
assert "No such page" in flat(missing)
assert "/search/" in missing and "/knowledge/" in missing
for internal in ("Traceback", "dk_public", "dk_site_render", str(ROOT), "Exception"):
    assert internal not in flat(missing), internal
print("PUBLIC_ERROR_OUTPUT_SAFE=PASS")


# --- accessibility and responsiveness -----------------------------------------


class Structure(html.parser.HTMLParser):
    """Enough of a parser to check the things that make a page usable."""

    def __init__(self) -> None:
        super().__init__()
        self.headings: list[int] = []
        self.landmarks: list[str] = []
        self.labels: list[str] = []
        self.inputs: list[str] = []
        self.tags: list[str] = []
        self.lang: str | None = None
        self.th_without_scope = 0
        self.images_without_alt = 0

    def handle_starttag(self, tag, attrs):
        attributes = dict(attrs)
        self.tags.append(tag)
        if tag == "html":
            self.lang = attributes.get("lang")
        if tag in ("h1", "h2", "h3", "h4"):
            self.headings.append(int(tag[1]))
        if tag in ("header", "nav", "main", "footer"):
            self.landmarks.append(tag)
        if tag == "label":
            self.labels.append(attributes.get("for", ""))
        if tag == "input":
            self.inputs.append(attributes.get("id", ""))
        if tag == "th" and "scope" not in attributes:
            self.th_without_scope += 1
        if tag == "img" and "alt" not in attributes:
            self.images_without_alt += 1


for name, text in sorted(PAGES.items()):
    parsed = Structure()
    parsed.feed(text)
    assert parsed.lang == "en", name
    assert parsed.headings.count(1) == 1, f"{name} must have exactly one h1"
    assert parsed.headings[0] == 1, f"{name} must open with its h1"
    for previous, current in zip(parsed.headings, parsed.headings[1:]):
        assert current <= previous + 1, f"{name} skips a heading level"
    assert "main" in parsed.landmarks and "nav" in parsed.landmarks, name
    assert parsed.th_without_scope == 0, name
    assert parsed.images_without_alt == 0, name
    assert 'href="#main"' in text and 'id="main"' in text, name
    assert 'aria-label="Primary"' in text, name
    for control in parsed.inputs:
        assert control in parsed.labels, (name, control)
assert 'for="q"' in PAGES["search/index.html"] and 'id="q"' in PAGES["search/index.html"]
assert ":focus-visible" in css, "keyboard focus must be visible"
assert ".skip" in css
print("PUBLIC_SITE_BASIC_ACCESSIBILITY=PASS")

assert 'name="viewport"' in home and "width=device-width" in home
assert "@media (max-width" in css
assert "grid-template-columns: repeat(auto-fit" in css
assert "overflow-x: auto" in css, "wide tables must scroll rather than break the page"
assert "max-width: var(--measure)" in css
print("PUBLIC_SITE_RESPONSIVE=PASS")

# Design serves the evidence: trust label, unknowns and provenance are styled as
# first-class content, and nothing hides an evidence state.
for required in (".badge", "ul.unknowns", "ul.provenance", ".empty", ".trust-note"):
    assert required in css, required
assert "display: none" not in css, "no evidence state may be hidden by styling"
assert "prefers-color-scheme: dark" in css
assert len(css) < 20_000 and len(search_js) < 20_000
print("PUBLIC_DESIGN_SUPPORTS_EVIDENCE_COMPREHENSION=PASS")


# --- boundaries and build model -----------------------------------------------

site_root = ROOT / "public-site"
assert (site_root / "content").is_dir() and (site_root / "assets").is_dir()
assert (site_root / "dataset").is_dir()
# Website source lives in one place, not scattered through domain directories.
for domain_dir in ("knowledge", "security", "api", "cases", "rules", "sources"):
    assert not list((ROOT / domain_dir).glob("*.css")), domain_dir
    assert not list((ROOT / domain_dir).glob("*.html")), domain_dir
print("PUBLIC_SITE_SOURCE_BOUNDARY_CLEAR=PASS")

gitignore = (ROOT / ".gitignore").read_text(encoding="utf-8")
assert "public-site/dist/" in gitignore, "rendered output is a build artifact"
assert "public-site/dataset" not in gitignore, "the dataset is committed and stale-guarded"
assert P.DATASET_DIR == Path("public-site") / "dataset"
print("PUBLIC_SITE_SOURCE_AND_BUILD_OUTPUT_DISTINCT=PASS")

assert cli_module.COMMAND_AUDIENCE["public-site"] == "internal"
help_all = subprocess.run(
    [sys.executable, str(CLI), "--help-all"], capture_output=True, text=True, check=True
).stdout
assert "public-site" in help_all
community_help = subprocess.run(
    [sys.executable, str(CLI), "--help"], capture_output=True, text=True, check=True
).stdout
assert "public-site" not in community_help, "site generation is not a community command"
docs = (ROOT / "docs" / "PUBLIC_SITE.md").read_text(encoding="utf-8")
site_readme = (ROOT / "public-site" / "README.md").read_text(encoding="utf-8")
for page_text in (docs, site_readme, (ROOT / "README.md").read_text(encoding="utf-8")):
    assert "public-site build" in page_text
assert "public-site serve" in docs
assert "GENERATED" in site_readme, "the generated directories must say so"
print("PUBLIC_SITE_BUILD_COMMAND_DOCUMENTED=PASS")

# The build produces a self-contained directory of static files.
assert "index.html" in SITE and "assets/site.css" in SITE and "robots.txt" in SITE
assert all(isinstance(text, str) for text in SITE.values())
assert not any(name.startswith("/") or ".." in name for name in SITE)
print("PUBLIC_SITE_DEPLOYMENT_ARTIFACT_PRODUCED=PASS")

ci = (ROOT / ".github" / "workflows" / "community.yml").read_text(encoding="utf-8")
assert re.search(r"^on:\n  push:\n  pull_request:\n", ci, re.MULTILINE), "the workflow must run on push and pull request"
job = re.search(r"^  public-site:\n(?P<body>(?:    .*\n)+)", ci, re.MULTILINE)
assert job, "missing public site validation job"
body = job.group("body")
assert "runs-on: ubuntu-latest" in body, "standard GitHub-hosted runner only"
assert "workflow_dispatch" not in ci, "validation must not be manual-only"
assert "test_public_site.py" in body
assert "public-site build" in body
assert "upload-artifact" in body and "public-site/dist" in body
for forbidden in ("git commit", "git push", "curl", "wget", "acquire", "--apply", "secrets."):
    assert forbidden not in body, forbidden
print("PUBLIC_SITE_CI_ARTIFACT=PASS")

# Domain pages are generated; only the four editorial pages are authored.
authored = {path.stem for path in (site_root / "content").glob("*.html")}
assert authored == {"home", "trust-model", "cli", "about", "api-docs"}
authored_text = "\n".join(
    (site_root / "content" / f"{name}.html").read_text(encoding="utf-8") for name in authored
)
for record_id in ("SA-CORE-2025-002", "api-lifecycle.", "change-record.", "case.drupal.solved."):
    assert record_id not in authored_text, record_id
# One advisory identifier is used as a worked example in the CLI and API guides.
# What must not appear is record *content*: an authored page restating a title,
# an affected-version range or a risk vector is the data fork this guards.
assert "SA-CORE-2025-001" in authored_text
# Identifiers used as example queries are bounded to one of each kind.
assert set(re.findall(r"SA-[A-Z]+-\d{4}-\d{3}", authored_text)) == {"SA-CORE-2025-001"}
assert len(set(re.findall(r"CVE-\d{4}-\d+", authored_text))) <= 1
# Record content is what must never be restated by hand.
for record_content in ("Cross site scripting", "AC:Basic", ">= 8.0.0", "10.3.13", "Moderately critical"):
    assert record_content not in authored_text, record_content
print("PUBLIC_DOMAIN_PAGES_NOT_MANUAL_DATA_FORK=PASS")


# --- read-only ----------------------------------------------------------------

canonical_before = {
    path: path.read_bytes()
    for directory in ("knowledge", "security", "api", "cases", "rules", "discovery", "sources")
    for path in sorted((ROOT / directory).rglob("*.json"))
}
P.build_dataset(ROOT)
build_site(P.build_dataset(ROOT))
for path, payload in canonical_before.items():
    assert path.read_bytes() == payload, f"the build changed {path}"
for forbidden in ("write_text", "write_bytes", "unlink", "mkdir", "rmtree"):
    assert forbidden not in render_source, forbidden
# The export writes exactly one directory, and only when asked to.
writes = [line for line in export_source.splitlines() if "write_bytes" in line or "write_text" in line]
assert len(writes) == 1 and "path.write_bytes(payload)" in writes[0]
print("PUBLIC_SITE_BUILD_ZERO_CANONICAL_TRUST_MUTATION=PASS")

# The site links no private service path. The repository-wide vocabulary
# and import scans live in test_community_boundary.py.
for private_path in ("/hosted/", "/admin/", "/login"):
    assert private_path not in export_source and private_path not in render_source, private_path
    assert private_path not in "\n".join(SITE.values()), private_path
print("PUBLIC_SITE_INDEPENDENT_OF_PRIVATE_CONSUMERS=PASS")
