#!/usr/bin/env python3
"""The scheduled acquisition and discovery workflows stay inside the trust model.

What is proved here, statically over the two workflow files and directly over
`scripts/dk_automation.py`:

1. Both workflows drive the released CLI entry points a maintainer would use,
   with `--due` cadence and a trust filter, never `--all`, and never a second
   engine.
2. Least privilege: the default token is read-only; only the persistence job
   holds `contents: write` and `pull-requests: write`; nothing else is granted;
   no secret other than the workflow token is referenced.
3. Persistence is bounded: the path allow-list admits evidence, state, review
   candidates, signals, dossiers and the derived public artifacts, and rejects
   trusted knowledge, rules, code, documentation and CI configuration. The
   negative case is exercised, not described.
4. No auto-merge, no bypass, no push to main; deterministic branches; one
   concurrency group per workflow that never cancels a run half-way.
5. The run summary is rendered from the engine's own report, and a report that
   records a trusted-knowledge mutation is refused.
6. A fetch failure keeps its failure status; the run exits non-zero and the
   summary lists the failure — it is never a silent "unchanged".
"""

from __future__ import annotations

import io
import json
import re
import subprocess
import sys
import tempfile
from contextlib import redirect_stdout
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

import dk_acquisition  # noqa: E402
import dk_automation  # noqa: E402
import dk_core  # noqa: E402

ROOT = dk_core.ROOT
WORKFLOWS = ROOT / ".github" / "workflows"

# --- 1. the workflows drive the released engines --------------------------------

EXPECTED = {
    "scheduled-acquisition": {
        "cron": "17 */6 * * *",
        "command": "python3 scripts/dk.py acquire --trust authoritative --due --quiet --report acquisition-report/run.json",
        "group": "scheduled-acquisition",
        "branch": "automation/source-acquisition",
        "operation": "acquisition",
        "run_job": "acquire",
    },
    "scheduled-discovery": {
        "cron": "43 3 * * *",
        "command": "python3 scripts/dk.py discover --trust ecosystem --due --quiet --report discovery-report/run.json",
        "group": "scheduled-discovery",
        "branch": "automation/discovery",
        "operation": "discovery",
        "run_job": "discover",
    },
}

texts = {name: (WORKFLOWS / f"{name}.yml").read_text(encoding="utf-8") for name in EXPECTED}


def job_body(text: str, job: str) -> str:
    match = re.search(rf"^  {job}:\n(?P<body>(?:    .*\n|\n)+?)(?=^  [a-z]+:\n|\Z)", text, re.MULTILINE)
    assert match, f"missing job {job}"
    return match.group("body")


for name, spec in EXPECTED.items():
    text = texts[name]
    assert re.search(
        rf'^on:\n  schedule:\n    - cron: "{re.escape(spec["cron"])}"\n  workflow_dispatch:\n', text, re.MULTILINE
    ), f"{name}: schedule + workflow_dispatch"
    assert text.count("cron:") == 1, "one schedule per workflow"
    assert spec["command"] in text, f"{name}: must run the released CLI entry point"
    assert "--all" not in text, f"{name}: never an unbounded acquisition"
    assert "--dry-run" not in text, f"{name}: a scheduled run persists what it observed"
    assert "AUTOMATION_BRANCH: " + spec["branch"] in text
    assert "OPERATION: " + spec["operation"] in text
    assert f"group: {spec['group']}\n  cancel-in-progress: false" in text, f"{name}: concurrency"
    assert "dk_automation.py check-paths" in text, f"{name}: path boundary must be enforced"
    assert "dk_automation.py paths" in text, "the allow-list is read from one place"
    assert "dk.py public-site build" in text and "dk.py api build" in text and "dk.py release-meta" in text, (
        "derived artifacts are regenerated by the canonical commands"
    )
    assert "dk.py validate" in text, "contracts are validated and the result reported"
print("SCHEDULED_WORKFLOWS_USE_RELEASED_ENGINES=PASS")

# The community validation workflow still never acquires or discovers.
community = (WORKFLOWS / "community.yml").read_text(encoding="utf-8")
assert "dk.py acquire" not in community and "dk.py discover" not in community
assert "schedule:" not in community
print("VALIDATION_WORKFLOW_NEVER_ACQUIRES=PASS")

# --- 2. least privilege ------------------------------------------------------------

ALLOWED_ACTIONS = {
    "actions/checkout@v4",
    "actions/setup-python@v5",
    "actions/upload-artifact@v4",
    "actions/download-artifact@v4",
}
for name, spec in EXPECTED.items():
    text = texts[name]
    assert re.search(r"^permissions:\n  contents: read\n", text, re.MULTILINE), f"{name}: default token is read-only"
    run_body = job_body(text, spec["run_job"])
    persist_body = job_body(text, "persist")
    assert "    permissions:\n      contents: read\n" in run_body, f"{name}: the engine job is read-only"
    assert "    permissions:\n      contents: write\n      pull-requests: write\n" in persist_body, (
        f"{name}: persistence holds exactly contents:write and pull-requests:write"
    )
    granted = set(re.findall(r"^\s+([a-z-]+): (read|write)$", text, re.MULTILINE))
    assert granted <= {("contents", "read"), ("contents", "write"), ("pull-requests", "write")}, granted
    for forbidden in ("actions: write", "administration:", "packages:", "security-events:", "id-token:"):
        assert forbidden not in text, (name, forbidden)
    assert "secrets." not in text, f"{name}: no secret beyond the workflow token"
    assert "github.token" in persist_body, "gh authenticates with the workflow token only"
    uses = set(re.findall(r"uses: (\S+)", text))
    assert uses <= ALLOWED_ACTIONS, f"{name}: only GitHub-maintained actions at the repository's pinned majors: {uses}"
    assert "@main" not in text and "@master" not in text
    assert "runs-on: ubuntu-latest" in run_body and "runs-on: ubuntu-latest" in persist_body
    assert "curl " not in text and "wget " not in text, "no ad-hoc network access outside the engine"
print("SCHEDULED_WORKFLOWS_LEAST_PRIVILEGE=PASS")

# --- 3 & 4. bounded persistence, no auto-merge, deterministic branches ---------------

for name, spec in EXPECTED.items():
    text = texts[name]
    persist_body = job_body(text, "persist")
    assert f'if: needs.{spec["run_job"]}.outputs.persist == \'true\'' in persist_body, (
        "persistence runs only when the engine job decided there is something to persist"
    )
    assert "no commit, no pull request" in text, "the no-change path is explicit"
    assert "gh pr merge" not in text and "auto-merge" not in text and "--auto" not in text, "never merges"
    assert "--admin" not in text and "bypass" not in text.replace("no bypass", ""), "never bypasses the ruleset"
    assert re.search(r"git push --force-with-lease=\"refs/heads/\$AUTOMATION_BRANCH:\$expected\" origin \"HEAD:refs/heads/\$AUTOMATION_BRANCH\"", text), (
        "the automation branch is pushed with a lease, never main"
    )
    assert "HEAD:refs/heads/main" not in text and "origin main" not in text.replace("origin/main", "")
    assert 'gh pr list --head "$AUTOMATION_BRANCH" --base main --state open' in persist_body, "an open PR is updated, not duplicated"
    assert "gh pr create --base main" in persist_body and "gh pr edit" in persist_body
    assert "check-paths" in persist_body, "the boundary is re-checked on the writing side"
    assert "co-authored-by" not in text.lower(), "automation commits carry no attribution trailer"
    assert "github-actions[bot]" in persist_body
print("SCHEDULED_PERSISTENCE_BOUNDED_AND_REVIEWED=PASS")

# --- the allow-list itself ------------------------------------------------------------

for operation in ("acquisition", "discovery"):
    allowed = dk_automation.allowed_paths(operation)
    assert "sources/snapshots/" in allowed and "sources/state/" in allowed
    assert not any(path.startswith("knowledge") for path in allowed)
    for derived in dk_automation.DERIVED_PATHS:
        assert derived in allowed
    for forbidden in dk_automation.FORBIDDEN_EXAMPLES:
        assert not dk_automation.is_allowed(operation, forbidden), (operation, forbidden)
        assert not dk_automation.is_allowed(operation, forbidden.rstrip("/") + "/anything.json"), (operation, forbidden)
assert "discovery/signals/" in dk_automation.allowed_paths("discovery")
assert "discovery/signals/" not in dk_automation.allowed_paths("acquisition"), "acquisition never writes signals"
assert "discovery/review/" not in dk_automation.allowed_paths("acquisition")

# Negative test: a change set that touches trusted knowledge is rejected as a
# whole, and the CLI exits non-zero on stdin shaped like `git status -z`.
attempted = [
    "sources/snapshots/drupal-core-releases/abc.txt",
    "sources/state/drupal-core-releases.json",
    "knowledge/records/drupal.security.twig-output-escaping.json",
]
try:
    dk_automation.check_paths("acquisition", attempted)
except dk_automation.AutomationBoundaryError as exc:
    assert "knowledge/records/drupal.security.twig-output-escaping.json" in str(exc)
else:
    raise AssertionError("a trusted-knowledge path was accepted")

for forbidden_path in (
    "rules/implementation/some-rule.json",
    "api/lifecycle/api-lifecycle.0c388a841dde8bea.json",
    "security/advisories/SA-CORE-2025-001.json",
    "scripts/dk_acquisition.py",
    ".github/workflows/community.yml",
    "docs/ACQUISITION_ENGINE.md",
    "sources/registry.json",
    "public-site/content/home.html",
    "public-site/dataset/domains/security.json",
    "release/sbom.json",
    "VERSION",
    "CHANGELOG.md",
):
    porcelain = f" M sources/state/x.json\x00 M {forbidden_path}\x00".encode()
    for operation in ("acquisition", "discovery"):
        result = subprocess.run(
            [sys.executable, str(SCRIPTS / "dk_automation.py"), "check-paths", "--operation", operation],
            input=porcelain,
            capture_output=True,
        )
        assert result.returncode == 1, (operation, forbidden_path, result.stdout, result.stderr)
        assert b"AUTOMATION_BOUNDARY_VIOLATION" in result.stderr and forbidden_path.encode() in result.stderr

# A rename out of an allowed path is seen on both names.
renamed = b"R  sources/state/a.json\x00knowledge/records/a.json\x00"
assert dk_automation.parse_porcelain(renamed) == ["sources/state/a.json", "knowledge/records/a.json"]
try:
    dk_automation.check_paths("acquisition", dk_automation.parse_porcelain(renamed))
    raise AssertionError("rename into knowledge/ was accepted")
except dk_automation.AutomationBoundaryError:
    pass

# The allowed change set passes, with the counts the workflow prints.
accepted = b"?? sources/snapshots/s/abc.txt\x00 M sources/state/s.json\x00?? discovery/candidates/source-change.s.0123456789abcdef.json\x00 M public-site/dataset/manifest.json\x00 M public-site/dataset/sources.json\x00 M public-api/examples/status.json\x00 M release/checksums.json\x00"
result = subprocess.run(
    [sys.executable, str(SCRIPTS / "dk_automation.py"), "check-paths", "--operation", "acquisition"],
    input=accepted,
    capture_output=True,
)
assert result.returncode == 0, result.stderr
assert b"AUTOMATION_CHANGED_PATHS=7" in result.stdout and b"AUTOMATION_FORBIDDEN_PATHS=0" in result.stdout
# An empty change set is the no-op path: nothing to persist, nothing rejected.
result = subprocess.run(
    [sys.executable, str(SCRIPTS / "dk_automation.py"), "check-paths", "--operation", "discovery"],
    input=b"",
    capture_output=True,
)
assert result.returncode == 0 and b"AUTOMATION_CHANGED_PATHS=0" in result.stdout
print("AUTOMATION_PATH_BOUNDARY_ENFORCED=PASS")
print("FORBIDDEN_PATH_MUTATION=REJECTED")

# --- 5 & 6. summaries come from the engine report; failures stay failures --------------

SOURCE_A = "<html><body><main><h1>Fixture</h1><p>Version one.</p></main></body></html>"
SOURCE_B = "<html><body><main><h1>Fixture</h1><p>Version two.</p></main></body></html>"


def fixture_root(root: Path, content: str) -> Path:
    document = root / "fixture.html"
    document.write_text(content, encoding="utf-8")
    source = {
        "id": "fixture-source",
        "title": "Fixture Source",
        "url": document.as_uri(),
        "trust": "authoritative",
        "enabled": True,
        "category": "fixture",
        "role": "Fixture source used by scheduled automation tests.",
        "collection_strategy": "change-detection",
        "check_cadence_days": 1,
        "lifecycle": "active",
        "checked_on": "2026-08-30",
        "provenance": "Local test fixture.",
        "version_semantics": {},
    }
    (root / "sources").mkdir(parents=True)
    (root / "sources" / "registry.json").write_text(dk_core.stable_json([source]), encoding="utf-8")
    (root / "knowledge" / "records").mkdir(parents=True)
    (root / "knowledge" / "records" / "sample.json").write_text(
        dk_core.stable_json({"id": "drupal.fixture.sample", "value": "trusted knowledge must not change"}),
        encoding="utf-8",
    )
    return document


with tempfile.TemporaryDirectory() as workspace:
    root = Path(workspace)
    document = fixture_root(root, SOURCE_A)
    first = dk_acquisition.acquire(root, source_ids=["fixture-source"])
    document.write_text(SOURCE_B, encoding="utf-8")
    changed = dk_acquisition.acquire(root, source_ids=["fixture-source"])
    document.unlink()
    failed = dk_acquisition.acquire(root, source_ids=["fixture-source"])

    for report, status in ((first, "first_observation"), (changed, "changed"), (failed, "unavailable")):
        assert report["results"][0]["status"] == status, (status, report["results"][0]["status"])
        assert report["trusted_knowledge_mutations"] == []

    numbers = dk_automation.acquisition_counts(changed)
    assert numbers["changed"] == 1 and numbers["snapshots_created"] == 1 and numbers["review_candidates_created"] == 1
    assert numbers["failures"] == 0 and numbers["attempted"] == 1
    markdown = dk_automation.summary_markdown("acquisition", changed, persistence="pending", validate_exit=0, engine_exit=0)
    assert "| changed | 1 |" in markdown and "| unchanged | 0 |" in markdown
    assert changed["run_id"] in markdown and "trusted knowledge mutations: `0`" in markdown

    # A fetch failure is a failure in the report, in the exit code and in the
    # summary. It is never counted as unchanged.
    failed_numbers = dk_automation.acquisition_counts(failed)
    assert failed_numbers["unavailable"] == 1 and failed_numbers["failures"] == 1 and failed_numbers["unchanged"] == 0
    assert dk_acquisition.run_exit_code(failed) == 1
    failed_markdown = dk_automation.summary_markdown("acquisition", failed, persistence="no-op", engine_exit=1)
    assert "Failures (a fetch failure is never reported as unchanged)" in failed_markdown
    assert "`fixture-source`: unavailable" in failed_markdown
    assert "| unchanged | 0 |" in failed_markdown

    # The commit message and pull request body are derived from the same report.
    message = dk_automation.commit_message("acquisition", changed)
    assert message.startswith("Scheduled acquisition: 1 changed, 0 unchanged, 0 failed\n")
    assert "Co-Authored-By" not in message and "review is required before merge" in message
    body = dk_automation.pull_request_body("acquisition", changed, validate_exit=1, engine_exit=0)
    assert "validation failed — expected when a pinned source changed" in body
    assert "sources/snapshots/" in body and "knowledge/" not in body.split("### What this pull request may contain")[1].split("### Review")[0]
    assert "close and reopen" in body

    # The CLI renders the same summary from the report on disk.
    report_path = root / "run.json"
    report_path.write_text(json.dumps(changed), encoding="utf-8")
    result = subprocess.run(
        [sys.executable, str(SCRIPTS / "dk_automation.py"), "summary", "--operation", "acquisition",
         "--report", str(report_path), "--persistence", "pr-created", "--validate-exit", "0", "--engine-exit", "0"],
        capture_output=True, text=True,
    )
    assert result.returncode == 0 and "persistence: `pr-created` on `automation/source-acquisition`" in result.stdout

    # A report that records a trusted-knowledge mutation is refused everywhere.
    tainted = dict(changed, trusted_knowledge_mutations=["knowledge/records/sample.json"])
    for render in (
        lambda: dk_automation.summary_markdown("acquisition", tainted, persistence="pending"),
        lambda: dk_automation.pull_request_body("acquisition", tainted, validate_exit=0, engine_exit=0),
    ):
        try:
            render()
            raise AssertionError("a tainted report was rendered")
        except dk_automation.AutomationBoundaryError:
            pass
    report_path.write_text(json.dumps(tainted), encoding="utf-8")
    result = subprocess.run(
        [sys.executable, str(SCRIPTS / "dk_automation.py"), "pr-body", "--operation", "acquisition", "--report", str(report_path)],
        capture_output=True, text=True,
    )
    assert result.returncode == 1 and "AUTOMATION_BOUNDARY_VIOLATION" in result.stderr
    digest_tainted = dict(changed, trusted_knowledge_digest={"before": "a", "after": "b"})
    try:
        dk_automation.summary_markdown("acquisition", digest_tainted, persistence="pending")
        raise AssertionError("a changed trusted-knowledge digest was rendered")
    except dk_automation.AutomationBoundaryError:
        pass

    # Discovery counts read the discovery report shape.
    discovery_report = {
        "run_id": "discovery.fixture", "started_at": "x", "completed_at": "y", "dry_run": False,
        "selection": {"requested": [], "trust": "ecosystem", "skipped_not_due": ["a", "b"]},
        "results": [{"source_id": "s", "status": "observed"}],
        "signals_created": ["signal.1"], "signals_updated": [], "signals_reused": ["signal.0"],
        "review_work_created": [], "corroboration_results": [{}], "failures": [], "engine_defects": [],
        "trusted_knowledge_mutations": [], "trusted_knowledge_digest": {"before": "d", "after": "d"},
    }
    discovery_numbers = dk_automation.discovery_counts(discovery_report)
    assert discovery_numbers == {
        "attempted": 1, "not_due": 2, "observed": 1, "unavailable": 0, "invalid_or_malformed": 0,
        "signals_created": 1, "signals_updated": 0, "signals_reused": 1, "review_work_created": 0,
        "corroboration_results": 1, "failures": 0, "engine_defects": 0,
    }
    assert dk_automation.commit_message("discovery", discovery_report).startswith(
        "Scheduled discovery: 1 new signal(s), 0 updated, 0 failed\n"
    )
print("AUTOMATION_SUMMARY_FROM_ENGINE_REPORT=PASS")
print("FETCH_FAILURE_NEVER_UNCHANGED=PASS")
print("TRUSTED_KNOWLEDGE_MUTATION_REFUSED=PASS")

# The helper itself is inert: it never runs git, never fetches, never writes.
helper_source = (SCRIPTS / "dk_automation.py").read_text(encoding="utf-8")
for forbidden in ("subprocess", "urllib", "socket", "write_text", "write_bytes", "os.system", "shutil"):
    assert forbidden not in helper_source, forbidden
print("AUTOMATION_HELPER_INERT=PASS")
print("AUTO_TRUSTED_KNOWLEDGE_MUTATION=NO")
print("AUTO_MERGE=NO")
print("HUMAN_REVIEW_REQUIRED=YES")
